### ISSUE TITLE
Error while installing capsule

### ISSUE THREAD

**Issue by saikumar0412** [clastix/coaks-baseline-architecture#19]
I am trying to install capsule and getting below error, could you please help.

```sh
Error: INSTALLATION FAILED: 1 error occurred:
	* Internal error occurred: failed calling webhook "owner.namespace.capsule.clastix.io": could not get REST client: unable to load root certificates: unable to parse bytes as PEM block

```
My cluster is aad enabled and have followed all steps as per below documentation 
https://github.com/clastix/coaks-baseline-architecture/blob/master/guides/01-create-aks-with-add.md

And getting error while doing helm install as per below doc
https://github.com/clastix/coaks-baseline-architecture/blob/master/guides/02-capsule-installation.md#installing-capsule-helm-chart

**Comment by saikumar0412** [comment]
One more detail to update is my cluster is a private cluster as I want to use private one

**Comment by prometherion** [comment]
Closing, duplicate of projectcapsule/capsule#1012
